In [259]:
import pandas as pd
import numpy as np

In [260]:
df = pd.read_csv('FashionDataset.csv')
df

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...,...
30753,21,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30754,22,Nan,Nan,Nan,Nan,Nan,Nan,Jewellery-Women
30755,23,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,24,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,25,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [261]:
df['Unnamed: 0'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [262]:
df.duplicated().sum()

np.int64(1331)

In [263]:
df.drop_duplicates()

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...,...
30752,20,shaya by caratlane,the wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
30753,21,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30755,23,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,24,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,25,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [264]:
df.columns = df.columns.str.strip()
df.columns

Index(['Unnamed: 0', 'BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice',
       'Discount', 'Category'],
      dtype='object')

In [265]:
df.drop(columns='Unnamed: 0', inplace=True)

In [266]:
df.columns

Index(['BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice', 'Discount',
       'Category'],
      dtype='object')

In [267]:
df.head(20)

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
5,kraus,wide ankle length cotton womens jeans - light ...,"Size:26,28,30,32,34",Rs\n1795,1615,10% off,Westernwear-Women
6,life,printed cotton blend collared womens regular d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1299,649,50% off,Westernwear-Women
7,fratini,embroidered wide neck polyester womens regular...,Size:XX-Large,Rs\n1299,649,50% off,Westernwear-Women
8,rare,floral polyester v neck womens flared dress - ...,"Size:Large,Medium,Small,X-Large",Rs\n2099,839,60% off,Westernwear-Women
9,rare,checks cotton boat neck womens regular top - b...,"Size:Medium,Small,X-Large",Rs\n1499,599,60% off,Westernwear-Women
10,life,solid square neck cotton womens regular dress ...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1499,749,50% off,Westernwear-Women
11,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n999,499,50% off,Westernwear-Women
12,life,printed blended round neck womens shift dress ...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1499,749,50% off,Westernwear-Women
13,life,printed jersey round neck womens t-shirt - black,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n599,299,50% off,Westernwear-Women
14,life,printed crepe square neck womens top - blue,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n999,499,50% off,Westernwear-Women
15,life,solid cotton collar neck womens shirt - pink,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1199,599,50% off,Westernwear-Women
16,life,solid cotton lycra round neck womens t-shirt -...,"Size:Large,Medium,Small,X-Small",Rs\n599,299,50% off,Westernwear-Women
17,life,printed cotton collar neck womens shirt - white,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1299,649,50% off,Westernwear-Women
18,van heusen,solid cotton v neck womens formal shirt - maroon,"Size:Large,Small,X-Small",Rs\n1999,799,60% off,Westernwear-Women
19,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1999,999,50% off,Westernwear-Women

In [268]:
df.tail(20)

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
30738,belleziya,combo pack set of 9 gold earrings and set of 3...,Nan,Nan,1699,Nan,Jewellery-Women
30739,clara,925 silver real pearl aki pendant with chain n...,Nan,Rs\n2199,2089,5% off,Jewellery-Women
30740,ayesha,womens metallic silver double drop with black ...,Nan,Rs\n298,149,50% off,Jewellery-Women
30741,clara,womens 925 sterling silver poppy mangalsutra t...,Nan,Rs\n2699,2564,5% off,Jewellery-Women
30742,fossil,vintage motifs multicolor bracelet - jf02854998,Nan,Nan,4195,Nan,Jewellery-Women
30743,giva,cubic zirconia silver push back clasp womens e...,Nan,Rs\n1699,1614,5% off,Jewellery-Women
30744,pretty women,womens jad/pearl golden chain - yellow,Nan,Rs\n499,424,15% off,Jewellery-Women
30745,estelle,womens candy bracelet with white american diam...,Nan,Nan,1299,Nan,Jewellery-Women
30746,jewelz,beautiful white crystal silver plated earrings,Nan,Rs\n1739,608,65% off,Jewellery-Women
30747,ayesha,womens metallic gold statement multilayered ch...,Nan,Rs\n798,399,50% off,Jewellery-Women
30748,jewelz,nine pieces combo fashion non-precious metal b...,Nan,Rs\n1339,468,65% off,Jewellery-Women
30749,pretty women,womens pearl golden drops,Nan,Rs\n449,381,15% off,Jewellery-Women
30750,tribe amrapali,sterling silver oval turquoise ear studs,Nan,Nan,1030,Nan,Jewellery-Women
30751,swarovski,constella stylish crystal white pierced earrings,Nan,Nan,8950,Nan,Jewellery-Women
30752,shaya by caratlane,the wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
30753,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30754,Nan,Nan,Nan,Nan,Nan,Nan,Jewellery-Women
30755,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [269]:
df.isna().sum()

BrandName    0
Deatils      0
Sizes        0
MRP          0
SellPrice    0
Discount     0
Category     0
dtype: int64

In [270]:
df['BrandName'] = df['BrandName'].str.upper()
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30754,NAN,Nan,Nan,Nan,Nan,Nan,Jewellery-Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,ESTELLE,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [271]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30758 entries, 0 to 30757
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BrandName  30758 non-null  object
 1   Deatils    30758 non-null  object
 2   Sizes      30758 non-null  object
 3   MRP        30758 non-null  object
 4   SellPrice  30758 non-null  object
 5   Discount   30758 non-null  object
 6   Category   30758 non-null  object
dtypes: object(7)
memory usage: 1.6+ MB

In [272]:
df.dtypes

BrandName    object
Deatils      object
Sizes        object
MRP          object
SellPrice    object
Discount     object
Category     object
dtype: object

In [273]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30754,NAN,Nan,Nan,Nan,Nan,Nan,Jewellery-Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,ESTELLE,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [274]:
df['BrandName'] = df['BrandName'].replace('NAN', np.nan, regex=True)

In [275]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30754,NaN,Nan,Nan,Nan,Nan,Nan,Jewellery-Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,ESTELLE,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [276]:
df['BrandName'].isna().sum()

np.int64(2726)

In [277]:
df['BrandName'].unique()

array(['LIFE', 'ONLY', 'FRATINI', 'ZINK LONDON', 'KRAUS', 'RARE',
       'VAN HEUSEN', nan, 'STOP', 'ZINK Z', 'COVER STORY', 'INFUSE',
       'ALLEN SOLLY', 'ALTLIFE', 'MADAME', 'ITI', 'LEVIS', 'AND',
       'FABALLEY', 'LATIN QUARTERS', 'SERA', 'ADIDAS', 'PEPE', 'INDYA',
       'JUNIPER', 'LOVEGEN', 'VERO MODA', 'FOREVER NEW', 'MAGRE',
       'INSENSE', 'CALVIN KLEIN UNDERWEAR', 'REEBOK', 'MARIE CLAIRE',
       'ENAMOR', 'SPYKAR', 'GET WRAPPED', 'CAMPUS SUTRA', 'DOLCE CRUDO',
       'EMBLAZE', 'GLOBAL DESI', 'JEALOUS 21', 'JOCKEY', 'CRIMSOUNE CLUB',
       'HAUTE CURRY', 'PROLINE', 'PUMA', 'IVY', 'VH FLEX', 'MYSHKA',
       'FEMINA FLAUNT', 'W', '109F', 'GIPSY', 'SAMSHEK', 'IS.U',
       'MISS CHASE', 'IRA SOLEIL', 'FILA', 'KAMI KUBI', 'TRAVEL BLUE',
       'VARANGA', 'DE MOZA', 'U.S. POLO ASSN.', 'VIP', 'JANASYA',
       'SKECHERS', 'LEE COOPER', 'AARKE', 'KASHISH', 'PEPE KIDS',
       'KENNETH COLE', 'ZINGG', 'AYESHA', 'ELLIZA DONATEIN', 'EROTISSCH',
       'BIBA', 'ED HARDY', 'BLACK PANTHER', 'MYSTERE PARIS',
       'MONTE CARLO', 'LOUIS PHILIPPE', 'MIMOSA', 'HIDESIGN', 'SOIE',
       'SWEET DREAMS', 'GIORDANO', 'KARROT', 'ALCIS', 'IMARA', 'CHARCHIT',
       'ATHOME', 'DISHA PATANI FOR GLAM LIFESTYLE', 'ALLEN SOLLY TRIBE',
       'ARIANA', 'LAVIE', 'RUKOOTINA', 'INDIAN TERRAIN', 'YURIS', 'DUKE',
       'HIGH STAR', 'SUTI', 'FASTRACK', 'SANAA', 'ZIYAA', 'MOTHERCARE',
       'JACK AND JONES', 'AURELIA', 'SHAYA BY CARATLANE', 'NEERUS',
       'AMUKTI', 'VARKALA SILK SAREES', 'FUSION BEATS', 'RITU KUMAR',
       'EMPORIO ARMANI', 'GAS', 'ARTEASTRI', 'BACK TO EARTH',
       'UNITED COLORS OF BENETTON', "LIL' STAR", 'NACHTMANN', 'CLOVIA',
       'TRIUMPH', 'AMANTE', 'NAYOMI', 'KAFTAN COMPANY', 'PARFAIT',
       'WACOAL', 'GROVERSONS PARIS BEAUTY', 'SLOGGI', 'ULTIMO', 'RECAP',
       'CATWALK', 'INC.5', 'CROCS', 'ESTATOS', 'TRESMODE',
       'LEMON & PEPPER', 'SHOETOPIA', 'NEW BALANCE', 'SOLETHREADS',
       'CERIZ', 'MODARE', 'CLARKS', 'DOUBLEU', 'GUESS', 'MONROW',
       'LAZERA SHOES', 'FLIPSIDE', 'VON WELLX', 'SIGNATURE SOLE',
       'HAVAIANAS', 'VENTO', 'SOLE HEAD', 'TITAN', 'FASTRACK WEARABLES',
       'ARMANI EXCHANGE', 'FOSSIL', 'MICHAEL KORS', 'CASIO', 'TIMEX',
       'ANNE KLEIN', 'TOMMY HILFIGER', 'DANIEL WELLINGTON',
       'TITAN WEARABLES', 'TISSOT', 'SWISS EAGLE', 'AMAZFIT', 'COACH',
       'SKAGEN', 'ESPRIT', 'HELIX', 'JUST CAVALLI', 'STEVE MADDEN',
       'TED BAKER', 'LAMEX', 'ELLE', 'VERSUS', 'FJORD', 'LAWMAN WATCHES',
       'VERSACE', 'CITIZEN', 'OLIVIA BURTON', 'XYLYS', 'STRAND BY OBAKU',
       'DIESEL', 'POLICE', 'FURLA', 'ZOOP', 'ALEXANDRE CHRISTIE',
       'ANTONIO BANDERAS', 'DOLCE & GABBANA', 'PACO RABANNE',
       'CAROLINA HERRERA', 'SKINN', 'ARCELIA', 'GUCCI', 'BURBERRY',
       'YVES SAINT LAURENT', 'JAGUAR', 'JEAN PAUL GAULTIER', 'ELIE SAAB',
       'CALVIN KLEIN', 'HUGO BOSS', 'ISSEY MIYAKE', 'AJMAL',
       'THIERRY MUGLER', 'CLINIQUE', 'DAVIDOFF', 'MERCEDES BENZ',
       'NINA RICCI', 'NIKE', 'YARDLEY LONDON', 'NARCISO RODRIGUEZ',
       'MOSCHINO', 'GIORGIO ARMANI', 'MONTBLANC', 'EMBARK', 'YVES ROCHER',
       'ELIZABETH ARDEN', 'FERRAGAMO', 'LANVIN', 'CLARINS', 'ASPEN',
       'JIMMY CHOO', 'MARYAJ', 'ABERCROMBIE & FITCH', 'TRUSSARDI',
       'BEVERLY HILLS POLO CLUB', 'MIU MIU', 'EVAFLOR', 'COLOUR ME',
       'CHOPARD', 'BETTY BARCLAY', 'LACOSTE', 'SUPERDRY', 'KENZO',
       'ESTEE LAUDER', 'S.OLIVER', 'CHLOE', 'RALPH LAUREN', 'MARC JACOBS',
       '4711', 'PLUM', 'MISSONI', 'BOUCHERON', 'ULRIC DE VARENS',
       'GIVENCHY', 'V CANTO', 'ALL GOOD SCENTS', 'KAMA AYURVEDA',
       'ROBERTO CAVALLI', 'AIGNER', 'DKNY', 'UNGARO', '18.21 MAN MADE',
       'E2O', 'PRETTY WOMEN', 'BELLEZIYA', 'ESTELLE', 'JEWELZ', 'CLARA',
       'GIVA', 'SHAZE', 'SWAROVSKI', 'MIA', 'TRIBAL ZONE', 'VOYLLA',
       'UNKNOWN BY AYESHA', 'REAL EFFECT', 'STOLN ACCESSORIES',
       'TRIBE AMRAPALI', 'ESVES', 'THE REAL EFFECT LONDON', 'ACCESSORIZE'],
      dtype=object)

In [278]:
df['Category'] = df['Category'].str.replace('-', ' ', regex=True)
df['Category'].unique()

array(['Westernwear Women', 'Indianwear Women',
       'Lingerie&Nightwear Women', 'Footwear Women', 'Watches Women',
       'Fragrance Women', 'Jewellery Women'], dtype=object)

In [279]:
df.head()

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear Women

In [280]:
df['Discount'] = df['Discount'].str.replace('[^0-9]','',regex=True)
df['Discount'] = df['Discount'].str.strip()

In [281]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50,Westernwear Women
...,...,...,...,...,...,...,...
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Nan,Nan,8950,,Jewellery Women
30754,NaN,Nan,Nan,Nan,Nan,,Jewellery Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65,Jewellery Women
30756,ESTELLE,womens gold plated double line fancy white and...,Nan,Nan,2799,,Jewellery Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,,Jewellery Women

In [282]:
df['Discount'].unique()

array(['50', '30', '40', '10', '60', '', '20', '41', '55', '73', '69',
       '47', '57', '70', '67', '33', '44', '35', '45', '65', '68', '17',
       '78', '25', '80', '64', '63', '32', '58', '26', '71', '75', '79',
       '61', '24', '62', '38', '43', '54', '23', '27', '42', '76', '72',
       '53', '12', '74', '56', '22', '66', '39', '15', '34', '85', '5',
       '77', '4', '51', '37', '48', '0', '52', '29', '28', '36', '31'],
      dtype=object)

In [283]:
df['Discount'] = df['Discount'].replace('',np.nan,regex=True)

In [284]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50,Westernwear Women
...,...,...,...,...,...,...,...
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Nan,Nan,8950,NaN,Jewellery Women
30754,NaN,Nan,Nan,Nan,Nan,NaN,Jewellery Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65,Jewellery Women
30756,ESTELLE,womens gold plated double line fancy white and...,Nan,Nan,2799,NaN,Jewellery Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,NaN,Jewellery Women

In [285]:
df['Discount'] = df['Discount'].astype(float)

In [286]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50.0,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30.0,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50.0,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40.0,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50.0,Westernwear Women
...,...,...,...,...,...,...,...
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Nan,Nan,8950,NaN,Jewellery Women
30754,NaN,Nan,Nan,Nan,Nan,NaN,Jewellery Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65.0,Jewellery Women
30756,ESTELLE,womens gold plated double line fancy white and...,Nan,Nan,2799,NaN,Jewellery Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,NaN,Jewellery Women

In [287]:
df.dropna(subset=['BrandName'], inplace=True)

In [288]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50.0,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30.0,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50.0,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40.0,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50.0,Westernwear Women
...,...,...,...,...,...,...,...
30752,SHAYA BY CARATLANE,the wing woman clover charm necklace,Nan,Nan,1250,NaN,Jewellery Women
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Nan,Nan,8950,NaN,Jewellery Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65.0,Jewellery Women
30756,ESTELLE,womens gold plated double line fancy white and...,Nan,Nan,2799,NaN,Jewellery Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,NaN,Jewellery Women

In [289]:
df['BrandName'].isna().sum()

np.int64(0)

In [290]:
df.replace('Nan',np.nan, inplace=True)

In [291]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50.0,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30.0,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50.0,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40.0,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50.0,Westernwear Women
...,...,...,...,...,...,...,...
30752,SHAYA BY CARATLANE,the wing woman clover charm necklace,NaN,NaN,1250,NaN,Jewellery Women
30753,SWAROVSKI,crystal stylish womens rodhium earrings,NaN,NaN,8950,NaN,Jewellery Women
30755,JEWELZ,ethnic gold plated jhumki earrings,NaN,Rs\n1839,643,65.0,Jewellery Women
30756,ESTELLE,womens gold plated double line fancy white and...,NaN,NaN,2799,NaN,Jewellery Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,NaN,NaN,1899,NaN,Jewellery Women

In [292]:
df['Deatils'].isna().sum()

np.int64(0)

In [293]:
df.isna().sum()

BrandName       0
Deatils         0
Sizes        4775
MRP          7023
SellPrice       0
Discount     7023
Category        0
dtype: int64

In [294]:
df['Sizes'] = df['Sizes'].fillna('Size: Error')

In [295]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50.0,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30.0,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50.0,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40.0,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50.0,Westernwear Women
...,...,...,...,...,...,...,...
30752,SHAYA BY CARATLANE,the wing woman clover charm necklace,Size: Error,NaN,1250,NaN,Jewellery Women
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Size: Error,NaN,8950,NaN,Jewellery Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Size: Error,Rs\n1839,643,65.0,Jewellery Women
30756,ESTELLE,womens gold plated double line fancy white and...,Size: Error,NaN,2799,NaN,Jewellery Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Size: Error,NaN,1899,NaN,Jewellery Women

In [296]:
df.isna().sum()

BrandName       0
Deatils         0
Sizes           0
MRP          7023
SellPrice       0
Discount     7023
Category        0
dtype: int64

In [297]:
df['MRP'] = df['MRP'].str.replace('[^0-9]','', regex=True)

In [298]:
df['MRP'] = df['MRP'].astype(float)

In [299]:
df['SellPrice'] = df['SellPrice'].astype(int)

In [300]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",1699.0,849,50.0,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",3499.0,2449,30.0,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",1199.0,599,50.0,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",2299.0,1379,40.0,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",1699.0,849,50.0,Westernwear Women
...,...,...,...,...,...,...,...
30752,SHAYA BY CARATLANE,the wing woman clover charm necklace,Size: Error,NaN,1250,NaN,Jewellery Women
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Size: Error,NaN,8950,NaN,Jewellery Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Size: Error,1839.0,643,65.0,Jewellery Women
30756,ESTELLE,womens gold plated double line fancy white and...,Size: Error,NaN,2799,NaN,Jewellery Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Size: Error,NaN,1899,NaN,Jewellery Women

In [301]:
df['MRP'] = df['MRP'].fillna(df['MRP'].mean())

In [302]:
df.isna().sum()

BrandName       0
Deatils         0
Sizes           0
MRP             0
SellPrice       0
Discount     7023
Category        0
dtype: int64

In [303]:
df['MRP'] = df['MRP'].astype(int)

In [304]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",1699,849,50.0,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",3499,2449,30.0,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",1199,599,50.0,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",2299,1379,40.0,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",1699,849,50.0,Westernwear Women
...,...,...,...,...,...,...,...
30752,SHAYA BY CARATLANE,the wing woman clover charm necklace,Size: Error,2508,1250,NaN,Jewellery Women
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Size: Error,2508,8950,NaN,Jewellery Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Size: Error,1839,643,65.0,Jewellery Women
30756,ESTELLE,womens gold plated double line fancy white and...,Size: Error,2508,2799,NaN,Jewellery Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Size: Error,2508,1899,NaN,Jewellery Women

In [305]:
df['SellPrice'] = df['SellPrice'].astype(int)

In [306]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",1699,849,50.0,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",3499,2449,30.0,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",1199,599,50.0,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",2299,1379,40.0,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",1699,849,50.0,Westernwear Women
...,...,...,...,...,...,...,...
30752,SHAYA BY CARATLANE,the wing woman clover charm necklace,Size: Error,2508,1250,NaN,Jewellery Women
30753,SWAROVSKI,crystal stylish womens rodhium earrings,Size: Error,2508,8950,NaN,Jewellery Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Size: Error,1839,643,65.0,Jewellery Women
30756,ESTELLE,womens gold plated double line fancy white and...,Size: Error,2508,2799,NaN,Jewellery Women
30757,ESTELLE,womens gold plated bridge designer mangalsutra...,Size: Error,2508,1899,NaN,Jewellery Women

In [307]:
df.dropna(subset=['Discount'], inplace=True)

In [308]:
df.dtypes

BrandName     object
Deatils       object
Sizes         object
MRP            int64
SellPrice      int64
Discount     float64
Category      object
dtype: object

In [309]:
df['Discount'] = df['Discount'].astype(int)

In [310]:
df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",1699,849,50,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",3499,2449,30,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",1199,599,50,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",2299,1379,40,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",1699,849,50,Westernwear Women
...,...,...,...,...,...,...,...
30746,JEWELZ,beautiful white crystal silver plated earrings,Size: Error,1739,608,65,Jewellery Women
30747,AYESHA,womens metallic gold statement multilayered ch...,Size: Error,798,399,50,Jewellery Women
30748,JEWELZ,nine pieces combo fashion non-precious metal b...,Size: Error,1339,468,65,Jewellery Women
30749,PRETTY WOMEN,womens pearl golden drops,Size: Error,449,381,15,Jewellery Women
30755,JEWELZ,ethnic gold plated jhumki earrings,Size: Error,1839,643,65,Jewellery Women

In [311]:
df.reset_index(drop=True)

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,LIFE,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",1699,849,50,Westernwear Women
1,ONLY,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",3499,2449,30,Westernwear Women
2,FRATINI,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",1199,599,50,Westernwear Women
3,ZINK LONDON,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",2299,1379,40,Westernwear Women
4,LIFE,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",1699,849,50,Westernwear Women
...,...,...,...,...,...,...,...
21004,JEWELZ,beautiful white crystal silver plated earrings,Size: Error,1739,608,65,Jewellery Women
21005,AYESHA,womens metallic gold statement multilayered ch...,Size: Error,798,399,50,Jewellery Women
21006,JEWELZ,nine pieces combo fashion non-precious metal b...,Size: Error,1339,468,65,Jewellery Women
21007,PRETTY WOMEN,womens pearl golden drops,Size: Error,449,381,15,Jewellery Women
21008,JEWELZ,ethnic gold plated jhumki earrings,Size: Error,1839,643,65,Jewellery Women

In [312]:
df.to_excel('Fashion_cleeaned.xlsx', index=False)